export * from './DetailCastSection';
export * from './DetailContentSection';
export * from './DetailTrailerSection';
export { default as DetailBackdrop } from './DetailBackdrop';
export { default as DetailPosterMovieSection } from './DetailPosterMovieSection';
export { default as DetailPosterTVSection } from './DetailPosterTVSection';
export { default as DetailSeasonSection } from './DetailSeasonSection';
export { default as DetailRecommendSection } from './DetailRecommendSection';
export { default as DetailCelebInfoSection } from './DetailCelebInfoSection';
export * from './LoadingPosterSection';
export * from './LoadingContentSection';
export * from './LoadingBackdrop';
export * from './LoadingCelebInfoSection';
